[package]
name = "rust-winapi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.132"
sysinfo = "0.32.0"
win-event-log = { git = "https://github.com/rustysec/win-event-log-rs" }
